//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulCool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_registry
    {
        public int ID { get; set; }
        public string Phone { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
    
        public virtual tb_datausers tb_datausers { get; set; }
    }
}
